spring.datasource.url=${AZURE_MYSQL_URL:jdbc:mysql://localhost:3306/innovateconnect?createDatabaseIfNotExist=true}
spring.datasource.username=${AZURE_MYSQL_USER:root}
spring.datasource.password=${AZURE_MYSQL_PASSWORD:cdac}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

frontend.url = ${FRONTEND_URL:http://localhost:5173}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=5098

# JWT
jwt.secret=ThisIsASecretKeyForJwtTokenGenerationInvConnectProject
jwt.issuer=InnovateConnect
jwt.audience=InnovateConnectUsers

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=innovateconnect02@gmail.com
spring.mail.password=zmwl xwhy lvjd hgcj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
